- name: Install Motif
  yum:
    name:
      - motif
      - motif-devel
      - qt
      - qt-devel
      - PyQt4
      - PyQt4-devel
      - plplot
      - plplot-devel
      - plplot-qt
      - plplot-pyqt
      - xerces-c
      - xerces-c-devel
    state: present
