---
- hosts: nodes
  remote_user: root
  roles:
    - basic
    - build-root
    - dev-hdf5
    - dev-sqlite
    - dev-cosine
- hosts: logins
  remote_user: root
  roles:
    - basic
    - build-root
    - dev-hdf5
    - dev-sqlite
    - dev-cosine
    - extra-tools
    - analysis-tools
    - monitoring-tools
