---
- hosts: nodes
  remote_user: root
  roles:
    - basic
    - build-root
    - dev-hdf5
    - dev-sqlite
    - dev-cosine

- hosts: logins1
  remote_user: root
  roles:
    - basic
    - build-root
    - dev-hdf5
    - dev-sqlite
    - dev-cosine
    - dev-openjdk
    - extra-tools
    - analysis-tools
    - monitoring-tools
