- name: Add EPEL repository
  yum:
    name: epel-release
    state: present

- name: Install bzip2
  yum:
    name: bzip2
    state: present

- name: Install tcsh
  yum:
    name: tcsh
    state: present

- name: Install development tools group
  yum:
    name: "@Development tools"
    state: present

- name: Install Git
  yum:
    name: git
    state: present

- name: Install Perl
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - perl
    - perl-Digest-MD5

- name: Install lsof
  yum:
    name: lsof
    state: present

- name: Install Editors
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - emacs
    - vim

- name: Install xorg-x11-xauth
  yum:
    name: xorg-x11-xauth
    state: present
